"""
Scans /posts/*.md, reads each file's frontmatter (title/date/excerpt),
and regenerates assets/js/posts-index.js — newest post first.

Run manually with: python scripts/generate_posts_index.py
Runs automatically via .github/workflows/update-posts-index.yml on every
push that touches /posts.
"""

import os
import re
from datetime import datetime

POSTS_DIR = "posts"
OUTPUT_FILE = "assets/js/posts-index.js"


def parse_frontmatter(text):
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    meta = {}
    if match:
        for line in match.group(1).split("\n"):
            if ":" in line:
                key, _, value = line.partition(":")
                meta[key.strip()] = value.strip()
    return meta


def parse_date(d):
    try:
        return datetime.strptime(d, "%B %d, %Y")
    except Exception:
        return datetime.min


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    posts = []
    if os.path.isdir(POSTS_DIR):
        for fname in sorted(os.listdir(POSTS_DIR)):
            if not fname.endswith(".md"):
                continue
            slug = fname[:-3]
            with open(os.path.join(POSTS_DIR, fname), encoding="utf-8") as f:
                content = f.read()
            meta = parse_frontmatter(content)
            posts.append({
                "slug": slug,
                "title": meta.get("title", slug),
                "date": meta.get("date", ""),
                "excerpt": meta.get("excerpt", ""),
            })

    posts.sort(key=lambda p: parse_date(p["date"]), reverse=True)

    lines = [
        "/* ============================================================",
        "   Post index — AUTO-GENERATED by scripts/generate_posts_index.py",
        "   via GitHub Actions on every push. Do NOT edit by hand —",
        "   edit the .md files in /posts instead; this file regenerates",
        "   automatically.",
        "   ============================================================ */",
        "",
        "const POSTS = [",
    ]
    for p in posts:
        lines.append("  {")
        lines.append(f'    slug: "{esc(p["slug"])}",')
        lines.append(f'    title: "{esc(p["title"])}",')
        lines.append(f'    date: "{esc(p["date"])}",')
        lines.append(f'    excerpt: "{esc(p["excerpt"])}"')
        lines.append("  },")
    lines.append("];")
    lines.append("")

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {len(posts)} posts to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
